services:
  surface:
    network_mode: bridge
    networks:
      - nautilus_network
  sim:
      profiles: ['sim']
      build: ../nautilus_sim/
      image: nautilus_sim
      container_name: sim_surface
      environment:
        - "ROS_HOSTNAME=sim"
        - "ROS_MASTER_URI=http://surface:11311"
      ports:
        - "8080:8080"
      stdin_open: true
      tty: true
      networks:
        - nautilus_network
      volumes:
        - type: bind
          source: ../nautilus_sim/models/nautilus
          target: /root/gzweb/http/client/assets/nautilus
        - type: bind
          source: ../nautilus_sim/nautilus_worlds
          target: /root/catkin_ws/src/nautilus_worlds

networks:
  nautilus_network:
    driver: bridge
